"""add campaigns and registrations

Revision ID: d33c29ba3077
Revises: 787aa2a994f4
Create Date: 2025-08-15 10:48:50.651700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33c29ba3077'
down_revision: Union[str, None] = '787aa2a994f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Crear tablas SIN intentar recrear el ENUM
    op.create_table('campaigns',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('type_of_waste', sa.String(length=50), nullable=False),
        sa.Column('collection_date', sa.DateTime(), nullable=False),
        sa.Column('zone', sa.String(length=100), nullable=False),
        sa.Column('max_capacity_kg', sa.Integer(), nullable=True),
        sa.Column('current_weight_kg', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_registrations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('campaign_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('address', sa.String(length=200), nullable=False),
        sa.Column('estimated_weight_kg', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='CREADA'),  # ✅ Usa String() en lugar de ENUM
        sa.Column('notes', sa.String(length=300), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assignments', sa.Column('registration_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('assignments_request_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'campaign_registrations', ['registration_id'], ['id'])
    op.drop_column('assignments', 'request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_request_id_fkey'), 'assignments', 'collection_requests', ['request_id'], ['id'])
    op.drop_column('assignments', 'registration_id')
    op.drop_table('campaign_registrations')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
