"""add slot_id to campaign_registrations

Revision ID: d4f417640cb7
Revises: 37533c860c29
Create Date: 2025-08-17 18:24:27.338581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4f417640cb7'
down_revision: Union[str, None] = '37533c860c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_requests')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('registration_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('campaign_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_id', sa.UUID(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_foreign_key(None, 'campaign_slots', ['slot_id'], ['id'])

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('current_weight_kg',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('current_weight_kg',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('campaign_registrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('slot_id')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('registration_id',
               existing_type=sa.UUID(),
               nullable=True)

    op.create_table('collection_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type_of_waste', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('CREADA', 'ASIGNADA', 'EN_CAMINO', 'EN_SITIO', 'COMPLETADA', 'FALLIDA', 'CANCELADA', name='requeststatus'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('collection_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_requests_pkey'))
    )
    # ### end Alembic commands ###
